#Configuration
#Keys and tokens redacted. These are generated by creating a new app at apps.twitter.com, substitute for _
MY_CONSUMER_KEY = '_'
MY_CONSUMER_SECRET = '_'
MY_ACCESS_TOKEN_KEY = '_'
MY_ACCESS_TOKEN_SECRET = '_'

TWEET_ACCOUNT = "primedate_bot" #The name of the account you're tweeting to.
